### ISSUE TITLE
Riemann not loading because of the EXTRA_CLASSPATH

### ISSUE THREAD

**Issue by hanynowsky** [exoscale/riemann-acknowledgement#3]
Hi,
I followed the instructions on README and enabled **EXTRA_CLASSPATH** in **/etc/sysconfig/riemann**, thus riemann would no more properly load?

``` bash
EXTRA_CLASSPATH=/usr/lib/riemann/riemann-acknowledgement.jar
```

*\* STACKTRACE:

```
INFO [2014-12-09 11:05:00,785] main - riemann.bin - PID 15323
```

``` java
ERROR [2014-12-09 11:05:00,826] main - riemann.bin - Couldn't start
java.lang.IllegalArgumentException: No value supplied for key: {:file "/var/log/riemann/riemann.log"}
        at clojure.lang.PersistentHashMap.create(PersistentHashMap.java:77)
        at riemann.logging$init.doInvoke(logging.clj:43)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at riemann.config$eval27.invoke(riemann.config:3)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.Compiler.loadFile(Compiler.java:7020)
        at clojure.lang.RT$3.invoke(RT.java:318)
        at riemann.config$include.invoke(config.clj:285)
        at riemann.bin$_main.doInvoke(bin.clj:61)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at riemann.bin.main(Unknown Source)
```

---
## *\* Riemann CONFIGURATION: http://pastebin.com/9s8FRcHi

If I change the exec line in /usr/bin/riemann to 

``` bash
exec java $EXTRA_JAVA_OPTS $OPTS  -cp "/usr/lib/riemann/*:"  riemann.bin "$CONFIG"
```
##  I get the same error.

``` bash
ls -lash /usr/lib/riemann/
total 121M
4,0K drwxr-xr-x   2 root    root    4,0K  8 déc.  17:23 .
4,0K dr-xr-xr-x. 26 root    root    4,0K 23 sept. 13:13 ..
4,0K -rw-r--r--   1 root    root      95 27 août  09:38 dash.config
 44M -rwxr-xr-x   1 riemann riemann  44M  8 déc.  16:53 riemann-acknowledgement-0.1.2-standalone.jar
 44M -rwxr-xr-x   1 riemann riemann  44M  8 déc.  17:23 riemann-acknowledgement.jar
 35M -rw-r--r--   1 riemann riemann  35M 18 juil. 19:22 riemann.jar
```

---

```
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```
- Latest Riemann RPM: 0.2.6
- Latest riemann-acknowledgement
- OS: CentOS 6.5 AMD64

**Comment by pyr** [comment]
Hi @hanynowsky,

As discussed on IRC, this is unrelated to riemann-acknowledgment.
